### ISSUE TITLE
IPython 3 missing dependencies

### ISSUE THREAD

**Issue by tbekolay** [conda/conda-recipes#256]
While some code of mine was running fine with IPython <= 2.4, since the upgrade IPython 3 I've had to install some additional dependencies. These should probably be added to the `ipython-notebook` recipe, though they may be `nbconvert` specific, if a new `ipython-nbconvert` recipe is desired.

The missing dependencies are `pygments` (already in `conda`) and [`mistune`](https://github.com/lepture/mistune), which would need a recipe added (it's a pure Python package though, so it should be pretty simple).

**Comment by marscher** [comment]
This is really urgent. This has broken a lot of stuff in my automated builds...

nbconvert needs jsonschema, which is not being dragged in automatically. BTW why is the IPython(-notebook) recipe in this repo still at 2.2.0 (master branch)? Which branch shall we use for pull requests?

**Comment by ccordoba12** [comment]
The dependencies were fixed a week ago in Anaconda. Do you still need the conda recipes?

One more thing: the recipes used here are not the same as those used in Anaconda. That's the reason of the mismatch.

**Comment by marscher** [comment]
They are not fixed!

ipython nbconvert still complains about missing dependencies:

https://travis-ci.org/markovmodel/PyEMMA/builds/53938490#L1391

This has run a few hours ago, installing Ipython3.

May I ask, why you do not share the recipes with the community anymore?

**Comment by ccordoba12** [comment]
How are you installing nbconvert?

**Comment by ccordoba12** [comment]
I see `jsonschema` as part of the `ipython-notebook` package, so where is the problem?

**Comment by marscher** [comment]
Isn't nbconvert a sub-command of ipython notebook?

**Comment by ccordoba12** [comment]
It's an IPython subcommand, but as I said, `jsonschema` is a dep of the notebook right now.

**Comment by marscher** [comment]
Am 11.03.2015 um 15:37 schrieb Carlos Cordoba:
> It's an IPython subcommand, but as I said, |jsonschema| is a dep of the
> notebook right now.
So why isn't being installed then?

**Comment by marscher** [comment]
Then its maybe my mistake, since I'm installing some of my doc
dependencies with pip, mainly because I've defined them in a
requirements file. Is there a way to conda install < requirements.txt?

**Comment by ccordoba12** [comment]
If you run

    conda install ipython

it *won't* be installed because that install the dependencies to run the terminal based version of IPython.

You need to run

    conda install ipython-notebook

**Comment by marscher** [comment]
got it :) Thank you.

**Comment by ccordoba12** [comment]
> Is there a way to conda install < requirements.txt?

You can take a look at

    conda env update --help

**Comment by marscher** [comment]
So I have to double book-keep my dependencies for pip and conda? Sorry
I'm getting off-topic right now.

**Comment by ccordoba12** [comment]
You can maintain your conda and pip deps in a single `environment.yml` file. This is a new feature in conda (just released about a month ago), so I'm not so sure how it works, but you can look for further details here:

https://github.com/conda/conda-env

Pinging also @chdoig because she knows more details about it.

**Comment by marscher** [comment]
Sounds good. Thank you! Will have a look.
